# COS60008 Introduction to data science
## Assignment 3 - Final Project, 2023, Semester 1
## Student Details: 
* Name: Kritika.
* Student id: 104361002
* Email: mailto:104361002@student.swin.edu.au
* Submission date: 28/06/2023
* Tutelab class: 3:30 - 5:30pm Thursday

### Task 3 - Test & Train Data Preparation

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
clean_data = pd.read_csv('clean_data.csv')

In [3]:
# Drop columns that are not needed
new_data = clean_data.drop(['Observer'], axis=1)
# 'Observer' column was dropped as it was not adding anything to this task.

new_data.to_csv('new_data.csv', index=False)
print(new_data.head())

   Year        Location Heat Wave Dry Spell Cold Wave Wet Spell  \
0  1980  East Carlburgh         N         N         Y         N
1  1980     Ramirezview         N         N         Y         N
2  1980  East Carloston         N         N         N         N
3  1981  East Carlburgh         N         N         Y         N
4  1981     Ramirezview         N         N         Y         N

   Avg Min Temp °C  Yr Rain mm Irrigation Crop Type Crop Damage    Yield
0             19.9      880.31          Y    Canola           Y   902.41
1             23.4      794.00          Y     Wheat           Y  1737.23
2             20.7     1089.66          N     Wheat           N  1498.37
3             20.1      789.53          Y     Wheat           Y  1612.48
4             22.9      682.08          Y     Maize           Y  1422.37

In [4]:
new_data

,Year,Location,Heat Wave,Dry Spell,Cold Wave,Wet Spell,Avg Min Temp °C,Yr Rain mm,Irrigation,Crop Type,Crop Damage,Yield
0,1980,East Carlburgh,N,N,Y,N,19.9,880.31,Y,Canola,Y,902.41
1,1980,Ramirezview,N,N,Y,N,23.4,794.00,Y,Wheat,Y,1737.23
2,1980,East Carloston,N,N,N,N,20.7,1089.66,N,Wheat,N,1498.37
3,1981,East Carlburgh,N,N,Y,N,20.1,789.53,Y,Wheat,Y,1612.48
4,1981,Ramirezview,N,N,Y,N,22.9,682.08,Y,Maize,Y,1422.37
...,...,...,...,...,...,...,...,...,...,...,...,...
115,2018,East Carlburgh,Y,N,N,Y,NaN,1695.80,Y,Maize,N,1388.00
116,2018,East Carloston,N,N,N,Y,NaN,1842.32,N,Maize,Y,1180.34
117,2019,East Carloston,N,N,N,Y,NaN,1904.86,N,Canola,Y,768.50
118,2019,East Carlburgh,Y,N,N,Y,NaN,1570.74,Y,Canola,N,994.37
119,2019,Ramirezview,Y,N,N,Y,NaN,1166.17,Y,Wheat,N,1771.76

In [5]:
new_data.dtypes

Year                 int64
Location            object
Heat Wave           object
Dry Spell           object
Cold Wave           object
Wet Spell           object
Avg Min Temp °C    float64
Yr Rain mm         float64
Irrigation          object
Crop Type           object
Crop Damage         object
Yield              float64
dtype: object

In [6]:
new_data['Location'] = new_data['Location'].astype('category').cat.codes
#changing categorical columns to numerical
#East Carlburgh: 0
#Ramirezview: 2 
#East Carloston: 1(these values were matched with new_data table)

In [7]:
#changing values of Y and N to 1 and 0
new_data['Crop Damage'] = new_data['Crop Damage'].map({'Y': 1.0, 'N': 0.0})

In [8]:
new_data['Heat Wave'] = new_data['Heat Wave'].map({'Y': 1.0, 'N': 0.0})

In [9]:
new_data['Cold Wave'] = new_data['Cold Wave'].map({'Y': 1.0, 'N': 0.0})

In [10]:
new_data['Dry Spell'] = new_data['Dry Spell'].map({'Y': 1.0, 'N': 0.0})

In [11]:
new_data['Wet Spell'] = new_data['Wet Spell'].map({'Y': 1.0, 'N': 0.0})

In [12]:
new_data['Irrigation'] = new_data['Irrigation'].map({'Y': 1.0, 'N': 0.0})

In [13]:
new_data['Crop Type'] = new_data['Crop Type'].astype('category').cat.codes
#canola: 0
#wheat: 2
#maize :1

In [14]:
mean_temperature = new_data['Avg Min Temp °C'].mean()
new_data['Avg Min Temp °C'].fillna(mean_temperature, inplace=True)

In [15]:
new_data["Avg Min Temp °C"] = new_data["Avg Min Temp °C"].round(2)

In [16]:
new_data

,Year,Location,Heat Wave,Dry Spell,Cold Wave,Wet Spell,Avg Min Temp °C,Yr Rain mm,Irrigation,Crop Type,Crop Damage,Yield
0,1980,0,0.0,0.0,1.0,0.0,19.90,880.31,1.0,0,1.0,902.41
1,1980,2,0.0,0.0,1.0,0.0,23.40,794.00,1.0,2,1.0,1737.23
2,1980,1,0.0,0.0,0.0,0.0,20.70,1089.66,0.0,2,0.0,1498.37
3,1981,0,0.0,0.0,1.0,0.0,20.10,789.53,1.0,2,1.0,1612.48
4,1981,2,0.0,0.0,1.0,0.0,22.90,682.08,1.0,1,1.0,1422.37
...,...,...,...,...,...,...,...,...,...,...,...,...
115,2018,0,1.0,0.0,0.0,1.0,21.78,1695.80,1.0,1,0.0,1388.00
116,2018,1,0.0,0.0,0.0,1.0,21.78,1842.32,0.0,1,1.0,1180.34
117,2019,1,0.0,0.0,0.0,1.0,21.78,1904.86,0.0,0,1.0,768.50
118,2019,0,1.0,0.0,0.0,1.0,21.78,1570.74,1.0,0,0.0,994.37
119,2019,2,1.0,0.0,0.0,1.0,21.78,1166.17,1.0,2,0.0,1771.76

In [17]:
new_data.to_csv('new_data.csv', index=False)

In [18]:
from sklearn.model_selection import train_test_split
#splitting of data into training and testing

In [19]:
#Dataset (a) - Yield as the target variable
# Drop the 'Yield' column from X
X_a = new_data.drop('Yield', axis=1)
# Set 'Yield' as the target y
y_a = new_data['Yield'] 

# Split the data into training and testing sets (80:20)
a_X_train, a_X_test, a_y_train, a_y_test = train_test_split(X_a, y_a, test_size=0.2, random_state=42)

# Saving the csv files
a_X_train.to_csv('a_X_train.csv', index=False)
a_X_test.to_csv('a_X_test.csv', index=False)
a_y_train.to_csv('a_y_train.csv', index=False)
a_y_test.to_csv('a_y_test.csv', index=False)

# Dataset (b) - Crop Damage as the target variable
# Drop the 'Crop Damage' column from X
X_b = new_data.drop('Crop Damage', axis=1) 
# Set 'Crop Damage' as the target y
y_b = new_data['Crop Damage'] 

# Split the data into training and testing sets (80:20)
b_X_train, b_X_test, b_y_train, b_y_test = train_test_split(X_b, y_b, test_size=0.2, random_state=42)

# Saving the CSV files
b_X_train.to_csv('b_X_train.csv', index=False)
b_X_test.to_csv('b_X_test.csv', index=False)
b_y_train.to_csv('b_y_train.csv', index=False)
b_y_test.to_csv('b_y_test.csv', index=False)

In [20]:
new_data

,Year,Location,Heat Wave,Dry Spell,Cold Wave,Wet Spell,Avg Min Temp °C,Yr Rain mm,Irrigation,Crop Type,Crop Damage,Yield
0,1980,0,0.0,0.0,1.0,0.0,19.90,880.31,1.0,0,1.0,902.41
1,1980,2,0.0,0.0,1.0,0.0,23.40,794.00,1.0,2,1.0,1737.23
2,1980,1,0.0,0.0,0.0,0.0,20.70,1089.66,0.0,2,0.0,1498.37
3,1981,0,0.0,0.0,1.0,0.0,20.10,789.53,1.0,2,1.0,1612.48
4,1981,2,0.0,0.0,1.0,0.0,22.90,682.08,1.0,1,1.0,1422.37
...,...,...,...,...,...,...,...,...,...,...,...,...
115,2018,0,1.0,0.0,0.0,1.0,21.78,1695.80,1.0,1,0.0,1388.00
116,2018,1,0.0,0.0,0.0,1.0,21.78,1842.32,0.0,1,1.0,1180.34
117,2019,1,0.0,0.0,0.0,1.0,21.78,1904.86,0.0,0,1.0,768.50
118,2019,0,1.0,0.0,0.0,1.0,21.78,1570.74,1.0,0,0.0,994.37
119,2019,2,1.0,0.0,0.0,1.0,21.78,1166.17,1.0,2,0.0,1771.76